FROM java:7

COPY . /usr/src/code
WORKDIR /usr/src/code

RUN find . -name "*.java" -print | xargs javac


# FROM fernandoacorreia/ubuntu-14.04-oracle-java-1.7

# COPY . /usr/src/code
# WORKDIR /usr/src/code
