# Pull base image.
FROM gelog/hadoop
MAINTAINER Feichao Qian <feqian@ucsd.edu>


####################
# HADOOP
####################

#ENV HADOOP_VERSION	2.6.0
#ENV HADOOP_HOME		/usr/local/hadoop
#ENV HADOOP_OPTS		-Djava.library.path=/usr/local/hadoop/lib/native
#ENV PATH		$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

# COPY files
COPY ./Data/ /MyData/
COPY ./Code/ /MyCode/

# Compile 

RUN javac -classpath `yarn classpath` -d ./MyCode ./MyCode/*.java \
	&& jar -cvf bigrams.jar -C ./MyCode . \
	&& mv bigrams.jar /usr/local/hadoop/share/hadoop/mapreduce/







